const WeatherActionTypes = {
  GET_WEATHER_START: 'GET_WEATHER_START',
  GET_WEATHER_SUCCESS: 'GET_WEATHER_SUCCESS',
  GET_WEATHER_FAILURE: 'GET_WEATHER_FAILURE',
  SET_WEATHER_UNITS: 'SET_WEATHER_UNITS',
  UPDATE_WEATHER_RANGE_PROGRESS: 'UPDATE_WEATHER_RANGE_PROGRESS',
  SET_CURRENT_SLIDER_TIME: 'SET_CURRENT_SLIDER_TIME',
  SET_CURRENT_WEATHER: 'SET_CURRENT_WEATHER'
}

export default WeatherActionTypes
