const WeatherActionTypes = {
  GET_WEATHER_START: 'GET_WEATHER_START',
  GET_WEATHER_SUCCESS: 'GET_WEATHER_SUCCESS',
  GET_WEATHER_FAILURE: 'GET_WEATHER_FAILURE',
  SET_WEATHER_UNITS: 'SET_WEATHER_UNITS',
  UPDATE_WEATHER_RANGE_PROGRESS: 'UPDATE_WEATHER_RANGE_PROGRESS'
}

export default WeatherActionTypes
